-- FAIRYMOOD production database schema
-- Run this file once in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- ---------- Helpers ----------
create or replace function public.normalize_phone(value text)
returns text
language sql
immutable
as $$
  select regexp_replace(coalesce(value, ''), '[^0-9]', '', 'g');
$$;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users a where a.user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- ---------- Catalog ----------
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text unique,
  name text not null check (char_length(name) between 2 and 160),
  category text not null check (category in ('camisole','outer','bottoms','accessories')),
  product_type text not null check (product_type in ('top','bottom','acc')),
  price numeric(12,2) not null check (price >= 0),
  image_url text not null,
  description text not null default '',
  colors text[] not null default '{}'::text[],
  stock integer not null default 0 check (stock >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coupons (
  code text primary key,
  percent_off numeric(5,2) not null check (percent_off > 0 and percent_off <= 100),
  active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now()
);

insert into public.coupons(code, percent_off, active)
values ('FAIRY10', 10, true)
on conflict (code) do update set percent_off = excluded.percent_off, active = excluded.active;

-- ---------- Customers / orders ----------
create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null unique,
  email text,
  address text,
  subdistrict text,
  district text,
  province text,
  zipcode text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_no text not null unique,
  customer_id uuid references public.customers(id) on delete set null,
  customer_name text,
  phone text,
  email text,
  address text,
  subdistrict text,
  district text,
  province text,
  zipcode text,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  discount numeric(12,2) not null default 0 check (discount >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  coupon_code text,
  payment_method text not null check (payment_method in ('card','promptpay','cod')),
  payment_status text not null default 'pending' check (payment_status in ('pending','unpaid','paid','failed','refunded')),
  status text not null default 'pending' check (status in ('awaiting_payment','pending','packing','shipped','completed','cancelled')),
  tracking_no text,
  stripe_session_id text unique,
  stock_released_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity between 1 and 10),
  size text not null default 'Freesize',
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_phone on public.orders(phone);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_products_active on public.products(active);

-- ---------- Updated-at trigger ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at before update on public.customers
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

-- ---------- RLS ----------
alter table public.products enable row level security;
alter table public.coupons enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products
for select to anon, authenticated
using (active = true);

drop policy if exists products_admin_read on public.products;
create policy products_admin_read on public.products
for select to authenticated
using (public.is_admin());

drop policy if exists products_admin_insert on public.products;
create policy products_admin_insert on public.products
for insert to authenticated
with check (public.is_admin());

drop policy if exists products_admin_update on public.products;
create policy products_admin_update on public.products
for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists products_admin_delete on public.products;
create policy products_admin_delete on public.products
for delete to authenticated
using (public.is_admin());

drop policy if exists customers_admin_all on public.customers;
create policy customers_admin_all on public.customers
for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists orders_admin_all on public.orders;
create policy orders_admin_all on public.orders
for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists order_items_admin_all on public.order_items;
create policy order_items_admin_all on public.order_items
for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- Coupons are intentionally not readable by anonymous users; server validates them.
drop policy if exists coupons_admin_all on public.coupons;
create policy coupons_admin_all on public.coupons
for all to authenticated
using (public.is_admin()) with check (public.is_admin());

-- ---------- Seed products (only if table is empty) ----------
do $$
begin
  if not exists (select 1 from public.products) then
    insert into public.products (name, category, product_type, price, image_url, description, colors, stock, active) values
    ('สายเดี่ยวลูกไม้ Fairy Lace Cami','camisole','top',390,'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=85','เสื้อสายเดี่ยวแต่งชายลูกไม้ สไตล์แฟรี่วินเทจ ผ้านุ่มพริ้วใส่สบาย แมทช์ง่ายกับกางเกงยีนส์หรือกระโปรงยาว',array['ดำ','ขาว'],18,true),
    ('เสื้อคลุมซีทรูไหมพรมบาง Fairy Shrug','outer','acc',450,'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=900&q=85','เสื้อคลุมแขนยาวเนื้อบางเบา เหมาะสำหรับสวมทับเสื้อสายเดี่ยว เพิ่มมิติและดีเทลให้ลุคดูมีเสน่ห์ยิ่งขึ้น',array['ขาว','เทา'],12,true),
    ('กระโปรงยาวชายระบาย Fairy Layered Skirt','bottoms','bottom',590,'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=900&q=85','กระโปรงเอวยางยืด ทรงเลเยอร์หลายชั้นสไตล์แฟรี่กรันจ์ เคลื่อนไหวสวย พริ้วไหวตามจังหวะเดิน',array['ดำ','เบจ'],9,true),
    ('สายเดี่ยวคอถ่วงสไตล์มินิมอล Silk Cami','camisole','top',350,'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=900&q=85','เสื้อสายเดี่ยวเนื้อผ้าซาตินพรีเมียม สายปรับได้ ให้ลุคดูเรียบหรู แต่ยังคงความแฟรี่ด้วยทรงคอถ่วง',array['ดำ','ขาว'],25,true),
    ('สร้อยคอจี้คริสตัลดวงดาว Fairy Necklace','accessories','acc',220,'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=85','สร้อยคอสีเงินรมดำ จี้รูปดาวและคริสตัล เติมเต็มลุคสไตล์ Fairycore ได้อย่างสมบูรณ์แบบ',array['เงิน'],31,true),
    ('กางเกงขายาวขากว้างผ้าลินิน Fairy Pants','bottoms','bottom',520,'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=900&q=85','กางเกงขายาวทรงหลวม ใส่สบาย ระบายอากาศได้ดีเยี่ยม จับคู่กับสายเดี่ยวครอปได้ลุคชิลๆ',array['ขาว','ดำ'],15,true),
    ('สายเดี่ยวถักโครเชต์ Vintage Crochet Top','camisole','top',420,'https://images.unsplash.com/photo-1516762689617-e1cffffd478d?auto=format&fit=crop&w=900&q=85','งานถักละเมียดละไม ลายดอกไม้เล็กๆ สไตล์โบฮีเมียนแฟรี่ แมทช์ง่ายกับกางเกงเอวสูง',array['ครีม','ดำ'],11,true),
    ('กระโปรงสั้นแต่งเชือกผูก Grunge Mini Skirt','bottoms','bottom',480,'https://images.unsplash.com/photo-1577900232427-18219b9166a0?auto=format&fit=crop&w=900&q=85','กระโปรงทรงเอบาดเล็กน้อย แต่งเชือกผูกด้านข้าง เพิ่มความเท่ความชิคให้กับเสื้อสายเดี่ยว',array['ดำ'],7,true);
  end if;
end $$;

-- ---------- Server-side order creation ----------
create or replace function public.create_order(
  p_name text,
  p_phone text,
  p_email text,
  p_address text,
  p_subdistrict text,
  p_district text,
  p_province text,
  p_zipcode text,
  p_payment_method text,
  p_coupon_code text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_phone text := public.normalize_phone(p_phone);
  v_customer_id uuid;
  v_order_id uuid;
  v_order_no text;
  v_subtotal numeric(12,2) := 0;
  v_discount numeric(12,2) := 0;
  v_total numeric(12,2) := 0;
  v_percent numeric(5,2) := 0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_qty integer;
  v_size text;
  v_resolved_items jsonb := '[]'::jsonb;
begin
  if coalesce(char_length(trim(p_name)),0) < 2 then raise exception 'กรุณากรอกชื่อผู้รับ'; end if;
  if char_length(v_phone) < 9 or char_length(v_phone) > 10 then raise exception 'เบอร์โทรศัพท์ไม่ถูกต้อง'; end if;
  if (select count(*) from public.orders where phone = v_phone and created_at > now() - interval '15 minutes' and status in ('awaiting_payment','pending','packing')) >= 3 then raise exception 'มีคำสั่งซื้อที่กำลังดำเนินการจากเบอร์นี้หลายรายการ กรุณารอสักครู่หรือติดต่อร้าน'; end if;
  if coalesce(char_length(trim(p_address)),0) < 3 or coalesce(char_length(trim(p_province)),0) < 2 then raise exception 'กรุณากรอกที่อยู่จัดส่งให้ครบ'; end if;
  if p_payment_method not in ('card','promptpay','cod') then raise exception 'วิธีชำระเงินไม่ถูกต้อง'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 20 then raise exception 'ตะกร้าสินค้าไม่ถูกต้อง'; end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := coalesce((v_item->>'quantity')::integer, 0);
    if v_qty < 1 or v_qty > 10 then raise exception 'จำนวนสินค้าต่อรายการต้องอยู่ระหว่าง 1-10 ชิ้น'; end if;

    select * into v_product
    from public.products
    where id = (v_item->>'product_id')::bigint
    for update;

    if not found or v_product.active is not true then raise exception 'มีสินค้าที่ไม่พร้อมจำหน่าย'; end if;
    if v_product.stock < v_qty then raise exception 'สินค้า % มีสต็อกไม่เพียงพอ', v_product.name; end if;

    v_size := left(coalesce(nullif(trim(v_item->>'size'),''),'Freesize'), 30);
    v_subtotal := v_subtotal + (v_product.price * v_qty);
    v_resolved_items := v_resolved_items || jsonb_build_array(jsonb_build_object(
      'product_id', v_product.id,
      'name', v_product.name,
      'unit_price', v_product.price,
      'quantity', v_qty,
      'size', v_size
    ));

    -- Reserve stock inside the same database transaction. If anything later fails, PostgreSQL rolls this back.
    update public.products set stock = stock - v_qty where id = v_product.id;
  end loop;

  if nullif(trim(coalesce(p_coupon_code,'')),'') is not null then
    select percent_off into v_percent
    from public.coupons
    where upper(code) = upper(trim(p_coupon_code))
      and active = true
      and (starts_at is null or starts_at <= now())
      and (ends_at is null or ends_at >= now());
    if not found then raise exception 'โค้ดส่วนลดไม่ถูกต้องหรือหมดอายุ'; end if;
    v_discount := round(v_subtotal * (v_percent / 100.0), 2);
  end if;

  v_total := greatest(0, v_subtotal - v_discount);
  if v_total < 10 and p_payment_method in ('card','promptpay') then raise exception 'ยอดชำระออนไลน์ขั้นต่ำ 10 บาท'; end if;

  insert into public.customers(name, phone, email, address, subdistrict, district, province, zipcode)
  values(trim(p_name), v_phone, nullif(trim(coalesce(p_email,'')),''), trim(p_address), trim(p_subdistrict), trim(p_district), trim(p_province), trim(p_zipcode))
  on conflict (phone) do update set
    name = excluded.name,
    email = coalesce(excluded.email, public.customers.email),
    address = excluded.address,
    subdistrict = excluded.subdistrict,
    district = excluded.district,
    province = excluded.province,
    zipcode = excluded.zipcode,
    updated_at = now()
  returning id into v_customer_id;

  v_order_no := 'FM-' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISS') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));

  insert into public.orders(
    order_no, customer_id, customer_name, phone, email, address, subdistrict, district, province, zipcode,
    subtotal, discount, total, coupon_code, payment_method, payment_status, status
  ) values (
    v_order_no, v_customer_id, trim(p_name), v_phone, nullif(trim(coalesce(p_email,'')),''), trim(p_address), trim(p_subdistrict), trim(p_district), trim(p_province), trim(p_zipcode),
    v_subtotal, v_discount, v_total, nullif(upper(trim(coalesce(p_coupon_code,''))),''), p_payment_method,
    case when p_payment_method = 'cod' then 'unpaid' else 'pending' end,
    case when p_payment_method = 'cod' then 'pending' else 'awaiting_payment' end
  ) returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(v_resolved_items)
  loop
    insert into public.order_items(order_id, product_id, product_name, unit_price, quantity, size)
    values(v_order_id, (v_item->>'product_id')::bigint, v_item->>'name', (v_item->>'unit_price')::numeric, (v_item->>'quantity')::integer, v_item->>'size');

  end loop;

  return jsonb_build_object(
    'order_id', v_order_id,
    'order_no', v_order_no,
    'subtotal', v_subtotal,
    'discount', v_discount,
    'total', v_total,
    'payment_method', p_payment_method,
    'items', v_resolved_items
  );
end;
$$;

revoke all on function public.create_order(text,text,text,text,text,text,text,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.create_order(text,text,text,text,text,text,text,text,text,text,jsonb) to service_role;

-- Release reserved inventory once (for expired/failed/cancelled online payments).
create or replace function public.release_order_stock(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item record;
  v_released timestamptz;
  v_payment_status text;
begin
  select stock_released_at, payment_status into v_released, v_payment_status from public.orders where id = p_order_id for update;
  if not found or v_released is not null or v_payment_status = 'paid' then return; end if;

  for v_item in select product_id, quantity from public.order_items where order_id = p_order_id and product_id is not null
  loop
    update public.products set stock = stock + v_item.quantity where id = v_item.product_id;
  end loop;

  update public.orders set stock_released_at = now(), updated_at = now() where id = p_order_id;
end;
$$;

revoke all on function public.release_order_stock(uuid) from public, anon, authenticated;
grant execute on function public.release_order_stock(uuid) to service_role;

-- Public order tracking requires BOTH order number and phone number.
create or replace function public.track_order(p_order_no text, p_phone text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_items jsonb;
begin
  select * into v_order
  from public.orders
  where upper(order_no) = upper(trim(p_order_no))
    and phone = public.normalize_phone(p_phone)
  limit 1;

  if not found then return null; end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'name', product_name,
    'quantity', quantity,
    'size', size,
    'unit_price', unit_price
  ) order by id), '[]'::jsonb)
  into v_items
  from public.order_items where order_id = v_order.id;

  return jsonb_build_object(
    'order_no', v_order.order_no,
    'customer_name', v_order.customer_name,
    'total', v_order.total,
    'payment_method', v_order.payment_method,
    'payment_status', v_order.payment_status,
    'status', v_order.status,
    'tracking_no', coalesce(v_order.tracking_no, '-'),
    'created_at', v_order.created_at,
    'items', v_items
  );
end;
$$;

revoke all on function public.track_order(text,text) from public, anon, authenticated;
grant execute on function public.track_order(text,text) to service_role;

-- Admin order update: restores stock automatically when an order is cancelled.
create or replace function public.admin_update_order(
  p_order_id uuid,
  p_status text,
  p_tracking_no text,
  p_payment_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_status text;
  v_item record;
  v_released timestamptz;
begin
  if not public.is_admin() then raise exception 'ไม่มีสิทธิ์ใช้งาน'; end if;
  if p_status not in ('awaiting_payment','pending','packing','shipped','completed','cancelled') then raise exception 'สถานะออเดอร์ไม่ถูกต้อง'; end if;
  if p_payment_status not in ('pending','unpaid','paid','failed','refunded') then raise exception 'สถานะการชำระเงินไม่ถูกต้อง'; end if;

  select status, stock_released_at into v_current_status, v_released from public.orders where id = p_order_id for update;
  if not found then raise exception 'ไม่พบออเดอร์'; end if;
  if v_current_status = 'awaiting_payment' and p_status = 'cancelled' then raise exception 'ออเดอร์นี้กำลังอยู่ใน Stripe Checkout กรุณารอให้ Session หมดอายุหรือจัดการจาก Stripe ก่อน'; end if;

  if p_status = 'cancelled' and v_current_status <> 'cancelled' and v_released is null then
    for v_item in select product_id, quantity from public.order_items where order_id = p_order_id and product_id is not null
    loop
      update public.products set stock = stock + v_item.quantity where id = v_item.product_id;
    end loop;
    update public.orders set stock_released_at = now() where id = p_order_id;
  end if;

  update public.orders set
    status = p_status,
    tracking_no = nullif(trim(coalesce(p_tracking_no,'')),''),
    payment_status = p_payment_status,
    updated_at = now()
  where id = p_order_id;
end;
$$;

revoke all on function public.admin_update_order(uuid,text,text,text) from public, anon;
grant execute on function public.admin_update_order(uuid,text,text,text) to authenticated;

-- Delete personal customer data while preserving anonymized accounting/order history.
create or replace function public.delete_customer_personal_data(p_customer_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'ไม่มีสิทธิ์ใช้งาน'; end if;
  if exists (
    select 1 from public.orders
    where customer_id = p_customer_id
      and status not in ('completed','cancelled')
  ) then
    raise exception 'ยังมีออเดอร์ที่กำลังดำเนินการ กรุณาปิดออเดอร์ให้เสร็จก่อนลบข้อมูลส่วนตัว';
  end if;

  update public.orders set
    customer_name = 'ลูกค้าที่ลบข้อมูลแล้ว',
    phone = null,
    email = null,
    address = null,
    subdistrict = null,
    district = null,
    province = null,
    zipcode = null,
    updated_at = now()
  where customer_id = p_customer_id;

  delete from public.customers where id = p_customer_id;
end;
$$;

revoke all on function public.delete_customer_personal_data(uuid) from public, anon;
grant execute on function public.delete_customer_personal_data(uuid) to authenticated;

-- ---------- Product image storage ----------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = true, file_size_limit = 5242880, allowed_mime_types = array['image/jpeg','image/png','image/webp'];

-- Anyone may view files from a public bucket; only admins can modify objects.
drop policy if exists product_images_admin_insert on storage.objects;
create policy product_images_admin_insert on storage.objects
for insert to authenticated
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists product_images_admin_update on storage.objects;
create policy product_images_admin_update on storage.objects
for update to authenticated
using (bucket_id = 'product-images' and public.is_admin())
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists product_images_admin_delete on storage.objects;
create policy product_images_admin_delete on storage.objects
for delete to authenticated
using (bucket_id = 'product-images' and public.is_admin());

-- ---------- Create your first admin ----------
-- 1) Supabase Dashboard > Authentication > Users > Add user
-- 2) Copy that user's UUID and run:
-- insert into public.admin_users(user_id, email)
-- values ('PASTE-AUTH-USER-UUID-HERE', 'your-admin@email.com');
